language: cpp

cache:
  - brew
  - apt: true

matrix:
  include:

    - os: linux
      sudo: true
      compiler: gcc
      install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install g++-4.8 texinfo zlib1g-dev
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90

        - if [ ! -d "$HOME/miniconda/bin" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && bash miniconda.sh -f -b -p $HOME/miniconda; fi
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
        - conda create -q -n prophyle -c etetoolkit -c bioconda python==3.4 ete3 bitarray parallel psutil scipy samtools || true
        - source activate prophyle

    - os: osx
      compiler: clang-3.7
      before_install:
        - brew update
        - brew tap homebrew/versions
      install:
        - export CXX="clang++-3.7" CC="clang-3.7"
        - brew install llvm37

        - if [ ! -d "$HOME/miniconda/bin" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh && bash miniconda.sh -f -b -p $HOME/miniconda; fi
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
        - conda create -q -n prophyle -c etetoolkit -c bioconda python==3.5 ete3 bitarray parallel psutil scipy samtools=1.2 || true
        - source activate prophyle

script:
  # see Makefile for details
  - unset PYTHONPATH
  # tests in the repo dir
  - make clean
  - make test_repo
  # tests in the package dir
  - make clean
  - make install
  - make test_package

cache:
  directories:
  - $HOME/miniconda
